### ISSUE TITLE
TinyB logic rely on custom manifest headers

### ISSUE THREAD

**Issue by splatch** [openhab/openhab-osgiify#13]
Some time ago I noticed that for whatever reason TinyB does not work with "new" versions of bluez. After bit of debugging I found that loading of library is dependent on `Specification-Title`, `Specification-Version` manifest entries which are omitted during osgification process. They need to be brought back in order to let TinyB still work as a library.

**Comment by J-N-K** [comment]
https://github.com/openhab/openhab-addons/pull/6369

**Comment by splatch** [comment]
> [openhab/openhab-addons#6369](https://github.com/openhab/openhab-addons/pull/6369)

I see it is fixed in addons, yet it is still not fixed in wrapper of library, shall this issue be abandoned in favor of addons fix? The openHAB addon embeds this dependency, but tinyb as a library is still useful on its own if we provide solution here.

**Comment by wborn** [comment]
Let's close this since tinyb is no longer used.

See: https://github.com/openhab/openhab-osgiify/pull/20
